from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.set_auto_page_break(auto=True, margin=15)
pdf.set_font("Arial", size=12)

lines = [
    "Secure Shipyard Tender Management Platform - Complete Project Plan",
    "===================================================================",
    "",
    "1. Project Overview:",
    "-------------------",
    "A secure, transparent web app for managing shipyard tenders to reduce corruption and ensure accountability.",
    "Allows vendors to submit sealed bids and admins to audit and award contracts fairly.",
    "",
    "2. What Are Tenders For?",
    "------------------------",
    "In the context of a shipyard, tenders are given for outsourcing or contracting various services, supplies, or infrastructure work.",
    "",
    "Here are realistic and common examples of tenders:",
    "",
    "Tender #1: Supply of Marine-Grade Steel Plates",
    "------------------------------------------------",
    "The shipyard requires 50 metric tons of marine-grade steel (Grade AH36 or equivalent) for hull construction and repairs.",
    "Vendors must deliver within 30 days of contract award.",
    "Vendors must submit:",
    "- Price quotation per ton",
    "- Delivery timeline",
    "- Material specification sheets (PDF upload)",
    "- Past supply experience (project references)",
    "Evaluation criteria:",
    "- Price",
    "- Material grade compliance",
    "- Delivery guarantee",
    "- Past performance",
    "",
    "Tender #2: Dry Dock Refurbishment Project",
    "-----------------------------------------",
    "Refurbishment of Dry Dock No. 2, including concrete repair, pump replacement, and anti-corrosion treatment.",
    "Project to be completed within 60 days.",
    "Vendors must submit:",
    "- Detailed project proposal with timeline",
    "- Budget breakdown",
    "- License and safety certifications",
    "- Worker availability and machinery list",
    "Evaluation criteria:",
    "- Experience in marine infrastructure",
    "- Timeline feasibility",
    "- Cost",
    "- Safety compliance",
    "",
    "Tender #3: Supply and Installation of CCTV Surveillance System",
    "-------------------------------------------------------------",
    "Install 40 high-definition CCTV cameras across the shipyard perimeter, with centralized monitoring, storage, and remote access.",
    "Vendors must submit:",
    "- Hardware specifications",
    "- Installation timeline",
    "- Warranty & support terms",
    "- Network and power integration plan",
    "Evaluation criteria:",
    "- Technical quality",
    "- Warranty period and support",
    "- Installation experience",
    "- Price and long-term reliability",
    "",
    "3. Key Features:",
    "----------------",
    "- Role-based authentication (Admin, Vendor)",
    "- Tender creation with deadlines and documents",
    "- Vendor bid submission with price, timeline, and file uploads",
    "- Audit log tracking all critical actions",
    "- Secure storage of bids with hashing/encryption",
    "- Admin dashboard for reviewing and awarding bids",
    "- Reporting and notifications",
    "",
    "4. Tech Stack:",
    "--------------",
    "Frontend: React.js + Tailwind CSS",
    "Backend: Node.js + Express.js",
    "Database: PostgreSQL (or MongoDB)",
    "Auth: JWT-based role management",
    "File Uploads: Multer (local or cloud storage)",
    "Hosting: Vercel (frontend), Render or Railway (backend + DB)",
    "",
    "5. 6-Week Roadmap:",
    "------------------",
    "Week 1: Setup & Authentication",
    "- GitHub repo, user roles, JWT auth",
    "",
    "Week 2: Tender Creation (Admin)",
    "- Create tenders with deadlines & attachments",
    "",
    "Week 3: Vendor Portal & Bid Submission",
    "- Vendors view open tenders & submit bids securely",
    "",
    "Week 4: Security & Audit Logging",
    "- Audit logs for all critical actions",
    "- Hash or encrypt bids",
    "",
    "Week 5: Admin Review & Awarding",
    "- View and compare bids, award contracts",
    "",
    "Week 6: Polish, Reporting & Deployment",
    "- Reports, notifications, charts, deploy",
    "",
    "6. Folder Structure:",
    "--------------------",
    "secure-tender-platform/",
    "├── client/               # React frontend",
    "│   ├── components/",
    "│   ├── pages/",
    "│   └── utils/",
    "├── server/               # Node backend",
    "│   ├── controllers/",
    "│   ├── middleware/",
    "│   ├── models/",
    "│   └── routes/",
    "├── uploads/              # File uploads (local/cloud)",
    "├── README.md",
    "",
    "7. Resume Highlight Example:",
    "----------------------------",
    "Secure Shipyard Tender Management Platform (React, Node, PostgreSQL)",
    "- Developed a secure web app to handle shipyard tenders and bids to prevent corruption",
    "- Implemented role-based auth and immutable audit logging",
    "- Deployed with real-time notifications and reporting dashboards",
]

for line in lines:
    pdf.multi_cell(0, 8, line)

pdf.output("Secure_Shipyard_Tender_Management_Project_Plan.pdf")
print("PDF generated: Secure_Shipyard_Tender_Management_Project_Plan.pdf")
